### ISSUE TITLE
Facility locator 508 metrics

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#59]
@crwallace we are building our vets.gov scorecard; want to include some 508 metrics!  i know we are tracking to 100% now!  do you have any data on old VA.gov 508 metrics?  either sitewide or a particular product that was worst in terms of 508 for our "before" metric.  (maybe facility locator??)  

any other 508 related metrics would be great too...especially if we can call out improvements for blind Veterans?

https://adhocteam.github.io/vets.gov-status/ 

thanks.

**Comment by koconnor719** [comment]
talked to courtney and have a number; can we replace the first metric (search locations and services since we already say this on front) with the following

Improved experience for blind Veterans; "Improved 79 design items that were accessibility challenges on the previous locator."  

can the icon/focus of this box be around blind Veterans--with a small note w/ the numbers and sentence above?  accessibility is the law so i don't want to focus too heavily  / use language that VA.gov was non-compliant:)

(i don't want be too negative about the old site saying it was non-compliant--b/c this could go external)

@staceylanger  pls. advise if you have concerns on this one.  i'm ok w/ it:)  but just checking.

**Comment by robertfairhead** [comment]
Updated facility locator scorecard with 79 accessibilities issues tile

**Comment by maryannbrody** [comment]
@koconnor719 @robertfairhead Let's say "Veterans who are blind or have low-vision" -- good practice to state the person (Veteran) before the disability (blind) when writing about disabilities since we are all people first. 

One question I have is about the 100% improved experience.. -- how did we measure for that? I'm a little concerned that that is not the whole truth. 508-compliance is the tip of the accessibility iceberg. Something might pass a 508 scan, but not actually work as intended in the wild if a person who is blind is using it. @crwallace and I observed some people use vets.gov with difficulty both at the BVA conference, and in the 508 office. 

I suggest we make this about 508, and less about measuring the % increase of UX. (IF we are 100% **508** compliant, not sure that we are -- @crwallace to confirm,) The metric can be something like: 

## **508 Compliance**
### **100%** 
Compliant according to Section 508 accessibility standards — which improves user experience for Veterans with disabilities like those who are blind or have low vision.

**Comment by robertfairhead** [comment]
I updated the language on the facility locator page to match Mary Ann's guidance and changed the metric tile on the main dashboard
