### ISSUE TITLE
top row grey boxes w/ metrics are different sizes?

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#74]
![screen shot 2016-09-30 at 5 18 43 pm](https://cloud.githubusercontent.com/assets/13770771/19007260/f6aa20ca-8731-11e6-9273-1d98c871e546.png)

**Comment by koconnor719** [comment]
box size looks different; and text doesn't seemed aligned in titles?

**Comment by robertfairhead** [comment]
This is fixed, but any further changes to the layout of the tiles (e.g., font sizes, alignment, etc.) will mess them up again. Maybe consider going with white background so that the height disparities are not so obvious?

![screen shot 2016-10-03 at 8 17 27 am](https://cloud.githubusercontent.com/assets/6646098/19037017/e38bda8a-8941-11e6-98fd-907e10350cde.png)

**Comment by koconnor719** [comment]
i defer to you guys on this.

**Comment by robertfairhead** [comment]
Ok, left the color boxes. Agree it adds to the visual attraction. Will continue to police that all remain the same as changes are made. Hopefully it will occur less frequently after the main design is settled.
