### ISSUE TITLE
facility locator GA traffic

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#76]
will we add traffic on   FL ?  appears to be missing.

**Comment by robertfairhead** [comment]
Facility locator traffic was not separated from overall site traffic until I reconfigured it last week (per my Slack message on Friday). It does not have historical data so will only begin collecting as of last week. We should wait a couple weeks before displaying so that a few data points are present on the graphs, unless you're certain you'd like to display partial data.

**Comment by koconnor719** [comment]
got it!  no need for partial data.
