### ISSUE TITLE
general font size - make readable for those over 40 pls:)

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#89]
@dannychapman can we increase the tiniest font size on the blue boxes and some of the text in headings ...it's soooo small--and those are the most compelling sentences about the products?   i know i'm old but i really can't read it easily--and i've gotten that feedback when i demo the site to other geezers like me as well:)

![screen shot 2016-09-30 at 7 15 35 pm](https://cloud.githubusercontent.com/assets/13770771/19009469/4abb198e-8742-11e6-8097-ff2bfa8ca6f0.png)

![screen shot 2016-09-30 at 7 18 24 pm](https://cloud.githubusercontent.com/assets/13770771/19009509/ba92c536-8742-11e6-8db9-4449ca0aaf98.png)

also on the "migration status" box on bottom too please:)

![screen shot 2016-09-30 at 7 19 52 pm](https://cloud.githubusercontent.com/assets/13770771/19009533/eff0578e-8742-11e6-9b60-f49e4ea12728.png)

and the sentence under Access:

![screen shot 2016-09-30 at 7 17 10 pm](https://cloud.githubusercontent.com/assets/13770771/19009492/8a6a1224-8742-11e6-98ea-bcca4acdbad3.png)

![screen shot 2016-09-30 at 7 21 34 pm](https://cloud.githubusercontent.com/assets/13770771/19009549/20e098ae-8743-11e6-997c-c5f5faddfa27.png)

**Comment by robertfairhead** [comment]
@kellyo the issue with increasing the font sizes is that we need to maintain a minimum number of characters per line so that the text remains easily readable.

Standard guidance is to aim for ~50 characters per line for body copy (e.g., non-headlines), cf. http://baymard.com/blog/line-length-readability among many others. We already pushed the font size up one the text inside the tiles so that we're done to about 35 characters per line, which is about as low as we can go without it getting awkward.

If the text really must go bigger, we'll have to redesign the grid layout away from the 4 across line up to allow more characters per line.

Please confirm you'd like this as it will take more than a day to complete. This will be a significant redesign and we'll have to retest the layout across all the browsers, etc. again afterwards.

**Comment by koconnor719** [comment]
i leave to you all, but it's really small.  i don't want to redesign the whole thing...so if you can address it great and if not just do what you think.  but it's super hard to read...

  @staceylanger

**Comment by robertfairhead** [comment]
We increased the font sizes everywhere noted above but in the tiles, for the reasons noted above those pose a specific problem with respect to characters per line.

We could make the text in the tiles taller but would have to make the font thinner to counter balance. Screenshots below.

<img width="1189" alt="screen shot 2016-10-03 at 6 59 01 pm" src="https://cloud.githubusercontent.com/assets/6646098/19057176/0456a2a4-899c-11e6-988b-2f76d50fdaf9.png">
<img width="1196" alt="screen shot 2016-10-03 at 7 00 19 pm" src="https://cloud.githubusercontent.com/assets/6646098/19057179/08015ef8-899c-11e6-8fab-6270f0cbd10a.png">

We still lose a few characters per line (for example the facility locator tile loses the AND) but the impact is mitigated and would not require a major grid redesign.

If you'd prefer the larger, thinner version please let me know.

**Comment by koconnor719** [comment]
thx so much for trying something...i think we should just stick w/ the vets.gov styles as you suggest.  .i think the thin font is not any easier to read. but thx again for trying something else...i guess old people will just have to zoom in:)  thx!!
