### ISSUE TITLE
boxes being clickable 

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#90]
@dannychapman is there any other design element you can add to boxes to make them look clickable--i see the arrow--but barely.  totally defer to you--just passing on 1 users feedback .  is it terrible design to put that little triangle in upper corner that looks like a page flip? or those little "more >"  ?  (don't mock this if it's a known worst practice--i hate citing design elements i like b/c they are all from 2002)

again i defer to you:)

**Comment by robertfairhead** [comment]
@kellyo @dannychapman current best practice is to minimize the "click-ability" affordances on websites because most users are very familiar with clicking on elements at this point. The standard ways to indicate "click-ability" now are to change on hover and use a rounded border edge (to suggest a button/tile/card), in-line with the design of vets.gov

Adding another more obtrusive element makes the design more visually busy without really adding valuable information to the user. The elements would be repeated on all the cards but add nothing distinguishing to them (once you've determined it's click-able the first time the added elements on the other tiles are redundant and distract from the actually different content on each card).

Danny added the arrows and drop shadows to increase the suggestion of "click-able" without distracting from the important content within the cards.

We would suggest not adding more visual elements to the cards to keep the focus on the important information inside them. If you feel strongly they must change though, we can do so.

**Comment by koconnor719** [comment]
ok, whatever you guys think.
