### ISSUE TITLE
check mobile view

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#91]
some text is getting cutoff ("dashboard" in title) and graphs are appearing w/ lines out of place

**Comment by robertfairhead** [comment]
Once the overall design is settled, especially #89 with its implications for a general redesign, we will do a final sweep to fix the layout issues. We have done one once before but the subsequently requested changes to the desktop view broke the mobile view again.

In order to maximize the efficiency on it, we would greatly prefer to avoid making further time-consuming, manual tweaks to fix the mobile views until the overall design is settled for sure.

**Comment by koconnor719** [comment]
you guys can decide the font issue--and if anything can be done to improve readability --without a whole lot of work of that point....  pls. just keep in mind going forward not all users can read this size font we are using.  i'm assuming that's not a great user experience. 

let's not do big redesign on this now--but can we pls. factor that into our style guide considerations for the future??  @staceylanger

**Comment by dannychapman** [comment]
I think we should keep the font size as-is. It's currently at 16px, which is a good industry standard for body text. In addition, this matches perfectly with both Vets.gov and USDS.

**Comment by dannychapman** [comment]
I will update the mobile header, but it's not worth touching until we refactor the dashboard using Vets.gov styles - this will take care of the header issue.

**Comment by robertfairhead** [comment]
I increased font sizes per #89 excepting the tile text, which remains at the 16px standard pending a decision on trading off text size for font width. As noted the font changes we do now will be undone when transitioning to vets.gov styles for public deployment.

We made some corrections to address the most egregious rendering issues on mobile (dashboard and lines in graphs), but highly suggest we do not do a full sweep for them until the style is finalized and transitioned to vets.gov standards as both will have significant impacts at this point, given our divergence on fonts from vets.gov styles.
